CREATE TYPE "public"."person_sex" AS ENUM('male', 'female');--> statement-breakpoint
CREATE TABLE "persons" (
	"id" text PRIMARY KEY NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"sex" "person_sex" NOT NULL,
	"family_head" boolean DEFAULT false NOT NULL,
	"family_member_id" text,
	"user_id" text,
	"cleaning" boolean DEFAULT true NOT NULL,
	"helper" boolean DEFAULT true NOT NULL,
	"start_conversations" boolean DEFAULT true NOT NULL,
	"return_visits" boolean DEFAULT true NOT NULL,
	"make_disciples" boolean DEFAULT true NOT NULL,
	"explain_beliefs" boolean DEFAULT true NOT NULL,
	"better_speech" boolean DEFAULT false NOT NULL,
	"bible_reading" boolean DEFAULT false NOT NULL,
	"baptized" boolean DEFAULT false NOT NULL,
	"prayer" boolean DEFAULT false NOT NULL,
	"sound" boolean DEFAULT false NOT NULL,
	"video" boolean DEFAULT false NOT NULL,
	"platform" boolean DEFAULT false NOT NULL,
	"microphone" boolean DEFAULT false NOT NULL,
	"elder" boolean DEFAULT false NOT NULL,
	"ministerial_servant" boolean DEFAULT false NOT NULL,
	"midweek_chairman" boolean DEFAULT false NOT NULL,
	"treasures_talk" boolean DEFAULT false NOT NULL,
	"pearls_quest" boolean DEFAULT false NOT NULL,
	"audience_analysis" boolean DEFAULT false NOT NULL,
	"analysis_talk" boolean DEFAULT false NOT NULL,
	"bible_study" boolean DEFAULT false NOT NULL,
	"study_reader" boolean DEFAULT false NOT NULL,
	"public_chairman" boolean DEFAULT false NOT NULL,
	"public_talk" boolean DEFAULT false NOT NULL,
	"watchtower_conductor" boolean DEFAULT false NOT NULL,
	"watchtower_reader" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "persons_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "persons" ADD CONSTRAINT "persons_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;